version: '3'
services:
  app:
    container_name: movoplus-frontend
    image: troy/movoplus:frontend
    command: sh -c "npm run start"
    env_file:
      - .env
    expose:
      - "3000"
    ports:
      - "3000:3000"
    
networks:
  default:
    